#!/bin/bash
# Quick install script for the Twitter Search Scraper Chrome Extension

echo "========================================="
echo "Twitter Search Scraper - Installation"
echo "========================================="
echo ""
echo "This extension can now scrape Twitter search results!"
echo ""
echo "OPTION 1: Load Unpacked Extension"
echo "--------------------------------"
echo "1. Open Chrome/Edge and go to: chrome://extensions/"
echo "2. Enable 'Developer mode' (toggle in top-right)"
echo "3. Click 'Load unpacked'"
echo "4. Select this folder: /workspaces/SA_forum_scraper"
echo ""
echo "OPTION 2: Install from ZIP (already created)"
echo "-------------------------------------------"
echo "1. Download: twitter-scraper-extension.zip"
echo "2. Unzip it on your local machine"
echo "3. Follow Option 1 steps with the unzipped folder"
echo ""
echo "HOW TO USE:"
echo "-----------"
echo "1. Navigate to Twitter (https://twitter.com)"
echo "2. Click the extension icon in your browser"
echo "3. Enter search term (e.g., 'Bitcoin')"
echo "4. Click 'Scrape Twitter Search'"
echo "5. Watch the console for progress (chrome://extensions/ → 'background page')"
echo ""
echo "Files created/modified:"
echo "  ✓ twitter-search-scraper.js (NEW)"
echo "  ✓ background.js (MODIFIED - added Twitter search handler)"
echo "  ✓ manifest.json (MODIFIED - added new script)"
echo "  ✓ popup.html (MODIFIED - added Twitter UI)"
echo "  ✓ popup.js (MODIFIED - added search button handler)"
echo ""
echo "Extension package: twitter-scraper-extension.zip (20KB)"
echo ""
echo "⚠️  WARNING: Scraping Twitter may violate their ToS. Use responsibly!"
echo ""
echo "========================================="
